export const TRANSCRIPT_TOGGLE = 'TRANSCRIPT_TOGGLE';
export const TRANSCRIPT_SEND_MESSAGE = 'TRANSCRIPT_SEND_MESSAGE';
export const TRANSCRIPT_PUSH_MESSAGE = 'TRANSCRIPT_PUSH_MESSAGE';
export const TRANSCRIPT_RESET_MESSAGE = 'TRANSCRIPT_RESET_MESSAGE';

export const SET_PERSONA_STATE = 'SET_PERSONA_STATE';

export const SCENE_START_VIDEO = 'SCENE_START_VIDEO';
export const SCENE_START_AUDIO = 'SCENE_START_AUDIO';
export const SCENE_CONNECTED = 'SCENE_CONNECTED';
export const SCENE_DISCONNECTED = 'SCENE_DISCONNECTED';

export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const HIDE_FEEDBACK = 'HIDE_FEEDBACK';

export const SET_FEATURES = 'SET_FEATURES';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const CHANGE_PANEL = 'CHANGE_PANEL';
export const TOGGLE_INFO_PANEL = 'TOGGLE_INFO_PANEL';
export const NOT_UNDERSTANDING = 'NOT_UNDERSTANDING';
export const TOGGLE_VIDEO_COLLAPSE = 'TOGGLE_VIDEO_COLLAPSE';
export const TOGGLE_PERSONA_SHRINK = 'TOGGLE_PERSONA_SHRINK';
export const SET_USER_SPEAKING = 'SET_USER_SPEAKING';
export const HIDE_WAYFINDER = 'HIDE_WAYFINDER';
export const SHOW_WAYFINDER = 'SHOW_WAYFINDER';
